// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantManagementSystem.Data;

#nullable disable

namespace RestaurantManagementSystem.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RestaurantManagementSystem.Models.Drinks", b =>
                {
                    b.Property<int>("drink_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("drink_id"), 1L, 1);

                    b.Property<string>("drink_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("drink_price")
                        .HasColumnType("real");

                    b.Property<string>("drink_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("drink_id");

                    b.ToTable("Drinks");
                });

            modelBuilder.Entity("RestaurantManagementSystem.Models.Employee", b =>
                {
                    b.Property<int>("e_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("e_id"), 1L, 1);

                    b.Property<DateTime>("DateOfJoining")
                        .HasColumnType("Date");

                    b.Property<string>("e_address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("e_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("e_password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("e_phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("e_roleID")
                        .HasColumnType("int");

                    b.Property<string>("e_username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("e_id");

                    b.HasIndex("e_roleID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("RestaurantManagementSystem.Models.Food", b =>
                {
                    b.Property<int>("food_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("food_id"), 1L, 1);

                    b.Property<string>("food_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("food_price")
                        .HasColumnType("real");

                    b.Property<string>("food_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("food_id");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("RestaurantManagementSystem.Models.Roles", b =>
                {
                    b.Property<int>("r_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("r_id"), 1L, 1);

                    b.Property<string>("r_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("r_id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("RestaurantManagementSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RestaurantManagementSystem.Models.Employee", b =>
                {
                    b.HasOne("RestaurantManagementSystem.Models.Roles", "Roles")
                        .WithMany()
                        .HasForeignKey("e_roleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
